### ISSUE TITLE
Invalid alignment value for posix_memalign

### ISSUE THREAD

**Issue by KailoKyra** [RichieSams/FiberTaskingLib#156]
I encountered the following error while trying to run the example on linux (Manjaro with linux 6.1.62 and g++ 13.2.1): 
 
```C++
FTL Assertion Failure: "posix_memalign". Expr: !result
Source File: /home/kailokyra/FiberTaskingLib/source/alloc.cpp:70
zsh: IOT instruction (core dumped)  ./ftl-example-triangle-num
```

Looking at the code, I noticed that the value passed to posix_memalign for alignment is 0 if the flag "FTL_FIBER_STACK_GUARD_PAGES" is not set, which is apparently incorrect as the documentation for posix_memalign states :

> [...] The address of the allocated memory will be a multiple of alignment, which must be a power of two and a multiple of sizeof(void *).

0 not being a power of two, the function returns EINVAL, and fails with the assert.
Forcing it to be at least sizeof(void*) fixes the issue, but the actual source of the error is using m_systemPageSize as the alignement argument in AlignedAlloc (in fiber.cpp) while it's set to 0.

**Comment by RichieSams** [comment]
Great find. Thank you for the thorough debugging. I'll look to get this fixed this week.
