### ISSUE TITLE
OS X tests compiled and running

### ISSUE THREAD

**Issue by underscorediscovery** [RichieSams/FiberTaskingLib#16]
I managed to get OS X running and compiling quite easily, so figured I would post the information here for discussion, before potentially opening a PR.

### Setup

I used homebrew for dependencies.
**make sure you update homebrew for boost >=1.58** i.e run `brew update` first

Started with cmake:
`brew install cmake` or `brew upgrade cmake`

Then boost:
`brew install boost`

### Build errors/fixes

Since there are concepts missing and compiler errors the following changes were needed to get started. Note that obviously the ideal is parity, but starting somewhere is good.

`/source/fiber_tasking_lib/thread_abstraction.h`
> `ThreadId` definition

```
#if defined(__linux__)
        typedef pid_t ThreadId;
#elif defined(__APPLE__)
       typedef mach_port_t ThreadId;
 #endif
```

> ThreadId function:

Note that the resulting ID returned is a uint64 ID, but the code in task_scheduler seems to be presuming they are id's from 0 and are used into an `[]` index. Unless I misread, but this probably needs to be looked at.

```
#if defined(__linux__)
	inline ThreadId FTLGetCurrentThreadId() {
		return syscall(SYS_gettid);
	}
#elif defined(__APPLE__)
	inline ThreadId FTLGetCurrentThreadId() {
		return pthread_mach_thread_np(pthread_self());
	}
#else
	#error Implement FTLGetCurrentThreadId for this platform
#endif
```

`eastl_defaults.cpp` (2 places)
> osx malloc is in `stdlib.h`

```
#include <cstdio>
#ifdef __APPLE__
#include <stdlib.h>
#else
#include <malloc.h>
#endif
```

`memory.h` 
>  std::align error
```
source/fiber_tasking_lib/tagged_heap_backed_linear_allocator.cpp:133:20: error: call to 'align' is ambiguous
        while ((userPtr = std::align(alignment, n, start, bufferSize)) == nullptr) {
```
Skipped custom align by `#ifndef __APPLE__` around it.
This could be a problem, but just hiding the custom definition appeared to work fine. 
(There is also a `int posix_memalign(void **, size_t, size_t);` in `stdlib.h` which may be of use somewhere here).

### Thread Affinity 

This one is more nuanced, so the simplest path was just NOP them for now.

[Here is a great post](http://yyshen.github.io/2015/01/18/binding_threads_to_cores_osx.html) on mac-wrapped parity functions that can be dropped in, [with accompanying code](https://github.com/yyshen/mbw/blob/osx/mbw.c) that handles pthread but not pthread_attr set affinity easily. Here is the documentation for the actual affinity [API](https://developer.apple.com/library/mac/releasenotes/Performance/RN-AffinityAPI/).

I'll take a look closer at the affinity now that everyone is running.

Short stop fixes:

- FTLCreateThread
 ```
	#ifndef __APPLE__
		// Set core affinity
		cpu_set_t cpuSet;
		CPU_ZERO(&cpuSet);
		CPU_SET(coreAffinity, &cpuSet);
		pthread_attr_setaffinity_np(&threadAttr, sizeof(cpu_set_t), &cpuSet);
	#endif
```

- FTLSetCurrentThreadAffinity
```
inline void FTLSetCurrentThreadAffinity(size_t coreAffinity) {
	#ifndef	__APPLE__
		cpu_set_t cpuSet;
		CPU_ZERO(&cpuSet);
		CPU_SET(coreAffinity, &cpuSet);

		pthread_setaffinity_np(pthread_self(), sizeof(cpu_set_t), &cpuSet);
	#endif
}
```

### Runtime error/fixes

From both the example and the tests, the same assertion:

```
[==========] Running 7 tests from 3 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from FunctionalTests
[ RUN      ] FunctionalTests.CalcTriangleNum
Assertion failed: (traits_type::minimum_size() <= size_), function basic_fixedsize_stack, file /usr/local/include/boost/context/fixedsize_stack.hpp, line 42.
Abort trap: 6
```

**fixed by increasing the stack size in task_scheduler.cpp**

I do wonder if this is not a similar cause for problems on the failed tests mentioned in other issues?

It appears the minimum it wants without configuration is `2^17`, I just tagged in a *x until it worked.

`globalArgs->g_taskScheduler.m_fiberSwitchingFibers[FTLGetCurrentThreadId()] = FTLCreateFiber(32768*4, `

There were 4 of these changes - so it should likely be a config value potentially passed in the initialize constructor or in a define value somewhere to allow flexibility.

# Results

![screen 2015-08-28 at 3 26 12 pm](https://cloud.githubusercontent.com/assets/236374/9553376/300570aa-4d99-11e5-873c-602205f8c2e8.png)

I can do a PR for various changes but think there are probably things to solve in a more unified way - like a no affinity flag to aid in initial portability and things like that.

Open to thoughts!

**Comment by RichieSams** [comment]
This is awesome!!! I've been meaning to test on OS X, but I couldn't get my VirtualBox to behave, and my motherboard doesn't play nicely with the hackintosh OS's.

<br />

Comments:

**ThreadId**
uint64 is good. The id just has to be unique and hashable. 

**std::align**
This comes from gcc not implementing std::align until version 5.1. I tried to use #ifdefs to ensure the custom definition is only present if gcc < 5.1 is being used, but I guess it didn't work. I'll look into it.

**Thread Affinity**
Core affinity isn't necessary for the library to function properly. However, as Christian mentioned in his talk, forcing affinity prevents thread evictions from cascading through all the worker threads. For example:

1. Worker Thread 1 get evicted by another thread on the OS.
2. Worker Thread 1 is re-scheduled, and looks for a core to run on
3. All the other worker threads have been running for "a while", so the scheduler evicts one of them (say Worker Thread 2) and starts Worker Thread 1 again.
4. Then Worker Thread 2 is re-scheduled; evicting Worker Thread 3.
5. And so on, and so on.
4. This process continues until all the worker threads have been evicted and re-started.

If we force thread affinity, a worker thread will only be evicted by external threads or kernel level threads.

Therefore, I would prefer to use the Apple API for thread affinity, and wrap everything in #ifdefs for the different systems.


**Minimum Stack Size**
Hmmm. That's really interesting. The config options sounds good.

I tried out the larger stack on Linux, but it's still segfaulting. :(



One last question: Are you using an actual Mac or is it a VM / virtualized by something like kvm?
I wonder if the Boost.Context is broken on virtualized hardware. I'll set up my linux dual boot and test it out there.

**Comment by underscorediscovery** [comment]
I'm testing on an actual Mac. I'll throw the working binaries up for download, and try  to run it in a VM on my Mac as well. I'll give it a try on linux too.

The thread affinity is the goal of course, 
I was already making progress on that front.

I'll tidy up and make some PR's soon.
(I'll keep the general PR's separate from the Mac specific ones.)
Thanks for the feedback

**Comment by RichieSams** [comment]
Awesome! Thank you for contributing. :)

**Comment by RichieSams** [comment]
Success!!!! https://travis-ci.org/RichieSams/FiberTaskingLib/jobs/78325370

**Comment by underscorediscovery** [comment]
Good deal :)
We can close this and I'll open another for the task affinity stuff.

**Comment by underscorediscovery** [comment]
Oh you could add that badge to the readme too, as a reminder

**Comment by RichieSams** [comment]
Working on it. Travis doesn't directly support seperate badges for the different os builds. But they have an api to query the status, so I think I'm going to whip up a quick little web heroku app that serves a badge.

**Comment by RichieSams** [comment]
Badges implemented and added: https://github.com/RichieSams/FiberTaskingLib/blob/master/README.md
