### ISSUE TITLE
Heavy synchronization activity

### ISSUE THREAD

**Issue by BrodyHiggerson** [RichieSams/FiberTaskingLib#27]
Hi there,

I've been trying different approaches to speed up my nasty N^2 algorithm in the core of my engine/server. Without any threading: ~44ms, with OpenMP: ~14.5ms, IntelTBB: ~8ms, FiberTaskingLib: ~14ms.

I did a bit of profiling of this with VTune, and found that a significant portion of time was spent in  synchronization.

![image](https://cloud.githubusercontent.com/assets/7245990/21928189/78419958-d9dd-11e6-910b-2f9ba3c105c7.png)

![image](https://cloud.githubusercontent.com/assets/7245990/21928206/93756146-d9dd-11e6-97a1-e4ce0cff75b5.png)

What are your thoughts on this?

**Comment by BrodyHiggerson** [comment]
Sorry, I was using a version of the repo from before you made some of the recent changes to the queueing/job stealing.

These are the new results for the same code and time/test conditions (mostly):

![image](https://cloud.githubusercontent.com/assets/7245990/21931561/3a178d96-d9f0-11e6-89b2-bb110f5c7791.png)

Currently hitting around 12-12.5ms, but am getting some weird hitching occasionally. Not sure if it's just the 8 threads hammering the CPU so hard the OS is having trouble printing the console seamlessly (I doubt that, because OpenMP thrashed it as well and the console had no problems). I'll keep an eye on it.

**Comment by BrodyHiggerson** [comment]
Oops, realized I had the work only divided down to something dumb like 1 task per thread, which explains the above results in terms of spending time stealing work. Here's 500 tasks instead of 8 ;)

![image](https://cloud.githubusercontent.com/assets/7245990/21932755/36342116-d9f6-11e6-85d3-ff048ef0c64c.png)

Memory:

![image](https://cloud.githubusercontent.com/assets/7245990/21932828/a584a720-d9f6-11e6-8678-39fba15fc75e.png)

**Comment by RichieSams** [comment]
This is really really cool info! Thanks for sharing.

I'd be really interested to see a capture with something like microprofile:
https://github.com/jonasmr/microprofile
(Note: If you use WaitForCounter(), you will need to break the profile scope into "before wait" and "after wait", since Microprofile won't be able to handle a fiber being migrated between threads).

    void MyFunction(....) {
        MICROPROFILE_ENTERI("root", "MyFunctionBeforeWait", MP_YELLOW);
        // Do stuffz
        // ....
        MICROPROFILE_LEAVE();

        taskScheduler->WaitForCounter(counter);

        MICROPROFILE_ENTERI("root", "MyFunctionAfterWait", MP_YELLOW);
        // Do more stuffz
        // ...
        MICROPROFILE_LEAVE();
    }

I'm wondering if the tasks are completing faster than you can feed the scheduler new ones. Though, from your last two screenshots, it looks like all your work is scheduled in the beginning. In this case, the worker threads will have nothing in their queues, and they will have to Steal() everything. Hence, why Steal() is so hot. Could you share a pseudo code of how you are scheduling your tasks? For example is it something like:

    // Create 500 tasks
    // ....

    auto counter = taskScheduler->AddTasks(...);
    
    taskScheuler->WaitForCounter(counter);

    // Repeat

This would help me in understanding the task flow.


One solution I can think of, would to be track the last successfully stolen queue per thread. So, when a thread tries to Steal() a task, it starts from the last queue it successfully stole from. Currently, it always starts at 1, and loops around. This would remove unnecessary Steal() calls, in the case of heavy imbalance in the queues between threads. 

As for using TBB concurrent containers, I have contemplated it. That said, I would have to heavily investigate their implementation, to make sure that it would be compatible with fibers. Currently, only the VC++ compiler has fiber-safe TLS optimizations; GCC and Clang do not. So if TBB containers use TLS, they can't be used in the library.

**Comment by BrodyHiggerson** [comment]
I'll have a go at getting that profiler working soon - I've not used something like that before (with the manually-specified timing points), but I'm not sure of its use in this case - my flow is extremely simplistic. It's this simplicity that made me want to try fibers, actually, since I don't yet need the incredible flexibility of IntelTBB's graph system (but didn't want to cook something up, myself - looking into this stuff is already self-indulgent enough right now, heh).

Your pseudocode is correct - I have an algorithm that is, at present, iterating over 1000 objects, with each of those loops then iterating n-1 objects (each other minus themselves), then while-looping over a collection of related data for between 0 and 3 iterations, starting from a point in said data that the CPU can't predict. It's pretty gnarly, but I create the tasks for the outer loop up-front since the work is 100% independent. I feel like fibers should destroy TBB eventually on something like this ;) One problem is that the work isn't completely balanced - there are calculations within the innermost loop that determine how much work there is to do, but overall I don't think it's too bad.

I've tried that commit of yours, and in my ~4am brain, I can't see much difference, but I'll have to dig into the profiler and compare some better numbers to give you more than just a hunch, but definitely no dramatic changes as far as I can see.

Anyway, I'm looking forward to seeing this library grow. Talk soon.

**Comment by RichieSams** [comment]
Yea, if your code flow is that simple, then Microprofile won't show much. It is kind of nice to visualize it though. Maybe I'm just a visual person. lol

Thanks for trying out the new commit. To be honest, I haven't done very much profiling myself of the library code. Having some "real world" examples like this is very helpful. I'm going to bust out VerySleepy and VTune and see how they look on some of my test examples.

**Comment by RichieSams** [comment]
So, if we can assume a strong memory model CPU, we can change the memory fence in Steal() to a compiler barrier, ie. change std::atomic_thread_fence() to std::atomic_signal_fence(). Testing on x86_64, this makes Steal much much faster.

Memory Barrier:
http://i.imgur.com/xJ5pkWm.png

Compiler Barrier:
http://i.imgur.com/l60GoX0.png

However, atm, I don't know of a good cross-platform way to do this.

**Comment by RichieSams** [comment]
That commit should lessen the memory synchronization time a little bit. That said, memory synchronization is still a large part of the overhead of the library. More work can be done on optimizations.

This is a project that launches 65000 empty tasks and then waits for them to complete:
![Empty Tasks](http://i.imgur.com/MeHcwI4.png)

Steal and Pop both suffer heavily from the fence and the atomic load
![Steal](http://i.imgur.com/wErjIOD.png)
![Pop](http://i.imgur.com/OoUStck.png)

That said, I currently don't know how I could optimize that any further.
One potential area of optimization is the waitingFibers checking:
![Waiting Fibers Checking](http://i.imgur.com/O0EZWPD.png)

It's also suffering from memory synchronization. I'm probably thrashing the cache. Perhaps we can put in a fast-out path, so we don't have to loop through the whole list of potential waiting fibers, and test their atomics.

Or another option would be to replace the current wait queue with something like the task queue.

**Comment by BrodyHiggerson** [comment]
@RichieSams I'll have a crack at testing these latest changes when I get the chance - I'm in the middle of some heavy refactoring and don't want to over-complicate, but I do want to give you some better feedback. I think I might try to provide you with a slimmed-down version of what I'm doing (or, hell, just link you a branch of the repo at some point) so you can see what's going on, if you'd like.

I forgot to mention on one of the other issues; did you want to connect on another medium to talk about the library further? No worries if not, but it'd be good to have that potential contact if I end up using it in my project for reals.

**Comment by RichieSams** [comment]
Awesome! No worries about not testing the new changes yet. I did a RFC on reddit, and as a result of their feedback, I may change the API a bit. 

I would love to see your use of the code. Like I said above, all my current tests are semi-contrived, so it would be great to put the library through its paces.

You can email me at: ad as tl ey {a t} gm ail <dot> com
Alternatively, if you use Discord, I have a small coding server, where we can message / talk: [https://discord.gg/ZWAHSwH](https://discord.gg/ZWAHSwH)

**Comment by BrodyHiggerson** [comment]
I dug up those posts of yours, but didn't see much in the way of drastic feedback/changes. Did I miss something?

It's very simple at the moment - not far off of what I mentioned previously. I'm currently very framework-y and early-on, so there's not much like the complexity of parallel gameplay code or anything just yet.

I am aboard the Discord :) Thanks for the invite.

**Comment by RichieSams** [comment]
Nothing too big. I'm probably going to remove the FTL_TASK_ENTRY_FUNCTION macro, so it will be up to the user to make the right function signature. (The compiler error should make it pretty obvious)

Next, I'm going to be looking into if I can get rid of the "mainTask". AKA, you can call TaskScheduler functions directly from the main thread. The reason I had gone the "mainTask" route, was that it makes it much much easier to detect when everything is done and clean up the resources afterwards. In addition, the old implementation of the fiber switching didn't like it if threads ended on different stacks than what they started on. I believe the new fiber asm file implementations fixes this. But I need to do some tests.

Those are the only changes.
