### ISSUE TITLE
sources from boost.context

### ISSUE THREAD

**Issue by olk** [RichieSams/FiberTaskingLib#36]
Please do not re-license code from Boost under Apache 2.0!
I suggest you move the Boost code to the folder 'third_party' as you did before.

**Comment by RichieSams** [comment]
Firstly, I would like to thank you for the work you have put into Boost::Context. I have reverted the commit that moved the asm files into source. In addtion, I have added more documentation to better exlain the copyrights and licenses of the third party code. Please let me know your comments. See 6e7f2a911f92ef3ea11ffbc1998c86f2b6378bd3 and cfeedb07eb89d406f07381d766c4e067563fe57d

**Comment by olk** [comment]
That's OK. I suggest to use the public API (execution_context<> or callcc()) instead the private fcontext-functions. execution_context<> or callcc() manage the stack (automatic allocation/deallocation) and prevent resuming an invalid (terminated) or already running context.

**Comment by RichieSams** [comment]
Thank you for the suggestions. I will look into execution_context<> and callcc()
