### ISSUE TITLE
Core affinity does not work

### ISSUE THREAD

**Issue by henrywiechert** [RichieSams/FiberTaskingLib#41]
Threads are not pinned to cores. This patch should fix it: https://github.com/henrywiechert/FiberTaskingLib/pull/1

**Comment by martty** [comment]
Could you open a pull request against this repo's master branch? The linked PR is against your fork's master branch.

**Comment by henrywiechert** [comment]
New PR created. Sorry for the mess.

**Comment by RichieSams** [comment]
No worries. Thank you for your contribution! Closed with PR#42
