### ISSUE TITLE
Create a build guide

### ISSUE THREAD

**Issue by RichieSams** [RichieSams/FiberTaskingLib#5]
Since we now have code for multiple platforms

**Comment by RichieSams** [comment]
Discuss Boost.Context build requirements

**Comment by BrodyHiggerson** [comment]
As a CMake noob, build guides are awesome >:) Love the look of the library so far and keen to get it going!

**Comment by RichieSams** [comment]
Yea..... CMake is a finicky beast. But it's what we're stuck with.

I want to push the library to full beta soon, so this should get added in the next week.

**Comment by BrodyHiggerson** [comment]
Awesome. I'm looking forward to digging through this. Strongly considering using it for the C++ game server I'm starting. That or Intel TBB. Have you used the latter by any chance and have any thoughts? Either way, thanks a bunch for this repo.

**Comment by RichieSams** [comment]
TBB is great, and production proven in a ton of different applications. 

While I highly encourage using FiberTaskingLib (if nothing else, so I can get some feedback), the library is pre-beta at the moment. Specifically, the task queue is "dumb", and will have a ton of contention. It shouldn't be that hard to make it "smart" (and that's what I'm working on currently), but, it's not quite ready yet.

Therefore, if you're considering FiberTaskingLib for any kind of production use, I would encourage you to wait for the Beta release, or use TBB / similar in the meantime.

**Comment by RichieSams** [comment]
Added in 0b27b502460cd14aa8e83643b8679d8efdb373eb & cce9b032dbcc03b8b4e1f9754c24a59b091d445b
