### ISSUE TITLE
wrong indexing

### ISSUE THREAD

**Issue by moritzpeter** [RichieSams/FiberTaskingLib#51]
https://github.com/RichieSams/FiberTaskingLib/blob/873420240dfcac3516dce667163449d9ce9837c7/source/atomic_counter.cpp#L121

Hey,

I think the indexing is broken. It should be:
`m_waitingFibers[readyFiberIndices[i]].PinnedThreadIndex`...

BR
Moritz

**Comment by RichieSams** [comment]
Oh, good catch. Thank you

**Comment by RichieSams** [comment]
Fixed in d4a09228eb96836d8b60e83969ec0517b90efdc3
