### ISSUE TITLE
LastSuccessfulSteal assignment

### ISSUE THREAD

**Issue by moritzpeter** [RichieSams/FiberTaskingLib#52]
https://github.com/RichieSams/FiberTaskingLib/blob/873420240dfcac3516dce667163449d9ce9837c7/source/task_scheduler.cpp#L411

Hey,

maybe it should be 
`tls.LastSuccessfulSteal = threadIndexToStealFrom;`

BR
Moritz

**Comment by RichieSams** [comment]
Thanks! Fixed in 82761e3c72398f59538fa897ab061c950e551360
