### ISSUE TITLE
AtomicCounter::WaitingFiberBundle ctor PinnedThreadIndexctor possibly wrong

### ISSUE THREAD

**Issue by ChemiaAion** [RichieSams/FiberTaskingLib#63]
I have noticed a _cosmetic_ difference between `AddFiberToWaitingList` default value for `pinnedThreadIndex` set to `std::numeric_limits<std::size_t>::max()`, here:
https://github.com/RichieSams/FiberTaskingLib/blob/cc59778a459181efe5f33f4611087d241f63b9eb/include/ftl/atomic_counter.h#L177

...and `AtomicCounter::WaitingFiberBundle` ctor set as ` PinnedThreadIndex(0)`, here:
https://github.com/RichieSams/FiberTaskingLib/blob/cc59778a459181efe5f33f4611087d241f63b9eb/source/atomic_counter.cpp#L56

I cannot point out if this is necessary (since `AddFiberToWaitingList` default will make it _right_) but IMO ctor should set it to an invalid value also, i.e.: `std::numeric_limits<std::size_t>::max()`

**Comment by RichieSams** [comment]
You're right. AddFiberToWaitingList should always overwrite the value, but it's good to set it to the invalid value at construction time. I'll make a fix. Thanks!
