### ISSUE TITLE
Add cmpxchg to AtomicCounter to Enable Mutexes

### ISSUE THREAD

**Issue by cwfitzgerald** [RichieSams/FiberTaskingLib#64]
In order to build a fiber based mutex AtomicCounter needs either cmpxchg. As for what to do with resuming the fibers, I think if the cmpxchg returns true, the fibers with the new value should be run.

**Comment by RichieSams** [comment]
Thoughts?

**Comment by cwfitzgerald** [comment]
Wow, I didn't expect you to come with an implementation! That looks fine, though it needs to be `lock` and `unlock` to comply with C++'s [BasicLockable](https://en.cppreference.com/w/cpp/named_req/BasicLockable) named requirement. I personally would also add a `lock_spin` function that spins in a [while/pause](https://godbolt.org/z/zkNeWc) loop, taking the amount of times to spin as the argument defaulted to say 100 or 1000.

**Comment by RichieSams** [comment]
For sure. You could also add the classic mutex optimization where you spin a few times, and then go to sleep.

**Comment by cwfitzgerald** [comment]
Alright, If you want I can get back to you with a PR for all these features by tomorrow.
