### ISSUE TITLE
Usage of the ftl scheduler

### ISSUE THREAD

**Issue by vamidi** [RichieSams/FiberTaskingLib#86]
Hi there,

I think I am using the library in a wrong way. Because I wanted to make a simple loading screen where I want load a bunch of textures in the background. When I made new tasks it holds everything before continue with doing anything else. Do I need to set something anywhere in order to continue my code after scheduler?

**Comment by RichieSams** [comment]
Hello,

I don't understand what you mean. Can you post some seudo code of what you're trying to do?

**Comment by vamidi** [comment]
```		

loading_screen.Tick(0.0f);

// Here I show my UI loading bar
m_Platform.GetRenderContext()->Present();

m_Platform.GetRenderContext()->EndRender();

m_Platform.GetRenderContext()->Swap();

// In here I run my scheduler like this
m_ResourceManager.Tick(0.0f); --> which only contains taskScheduler.Run(25, MainTask, nullptr);
```

**Comment by RichieSams** [comment]
Ah. Yes, that will be very inefficient. `taskScheduler::Run()` re-initializes everything. Ideally, all your code should be inside the MainTask. Something like:

```cpp
void MainTask(ftl::TaskScheduler *taskScheduler, void *arg) {
    // Code ....
    
    
    loading_screen.Tick(0.0f);

    // Here I show my UI loading bar
    m_Platform.GetRenderContext()->Present();

    m_Platform.GetRenderContext()->EndRender();

    m_Platform.GetRenderContext()->Swap();

    // In here I run my scheduler like this
    // m_ResourceManager.Tick(0.0f);
    ftl::AtomicCounter counter;
    taskScheduler::AddTask(ftl::Task{ResourceManagerTickFunc, 0.0f}, &counter);
    
    taskScheduler::WaitForCounter(&counter, 0);
    
    
    // More code ...
}

int main(int argc, char *argv) {
    ftl::TaskScheduler taskScheduler;
    taskScheduler.Run(25, MainTask);

    return 0;
}
```

**Comment by vamidi** [comment]
Oh like that so your whole code becomes part of the system. So now that you add the task to the scheduler will that run on a seperate thread? or because 25 is the max tasks before we start a new thread/worker?

**Comment by RichieSams** [comment]
`taskScheduler::AddTask()` adds the Task to the queue and then returns. Internally, FTL has a pool of worker threads. One of these threads will pick up the task and execute it. 

`taskScheduler::WaitForCounter()` will block until the Task has finished. You are free to do other work between `AddTask()` and `WaitForCounter()`. That's the beauty of a Task system.

In the above example, 25 is the size of the Fiber pool. 

```cpp
/**
 * Initializes the TaskScheduler and then starts executing 'mainTask'
 *
 * NOTE: Run will "block" until 'mainTask' returns. However, it doesn't block in the traditional sense; 'mainTask'
 * is created as a Fiber. Therefore, the current thread will save it's current state, and then switch execution to
 * the the 'mainTask' fiber. When 'mainTask' finishes, the thread will switch back to the saved state, and Run()
 * will return.
 *
 * @param fiberPoolSize     The size of the fiber pool. The fiber pool is used to run new tasks when the current task is waiting on a counter
 * @param mainTask          The main task to run
 * @param mainTaskArg       The argument to pass to 'mainTask'
 * @param threadPoolSize    The size of the thread pool to run. 0 corresponds to NumHardwareThreads()
 * @param behavior          The behavior of the threads after they have no work to do.
 */
void Run(uint fiberPoolSize, TaskFunction mainTask, void *mainTaskArg = nullptr, uint threadPoolSize = 0,
		 EmptyQueueBehavior behavior = EmptyQueueBehavior::Spin);
```

If you do a lot of Task chaining / waits, you will need more Fibers. That said, Fibers require memory for their stacks.

**Comment by vamidi** [comment]
Alright nice thanks! But if we look at your answer for example, The function `ResourceManagerTickFunc` will be executed, but I need my code before that to run everytime without getting blocked by `ResourceManagerTickFunc`. Is this then still the right system to use?

**Comment by RichieSams** [comment]
Yes. It could work. Instead of doing `taskScheduler::AddTask()` and ` taskScheduler::WaitForCounter()` each frame, you could do `AddTask()` once, and then check the status each frame via `counter.Load()` and check if it's 0.

**Comment by vamidi** [comment]
Oh nice I will try it soon! Thank you for your reaction and time!

**Comment by RichieSams** [comment]
You're welcome :)
